<a href="https://colab.research.google.com/github/kavita0704/220512_kavita/blob/main/Another_copy_of_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week-1 Assignment

**Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.**

P.S. You might find use of functions which you have never used before.So feel free to google

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Section0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Section1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
import numpy as np
def isValid(A,B):

   if A.shape[1] == B.shape[0]:
        result = np.dot(A, B)
        return result



##### (ii) Using loops (without using numpy)

In [ ]:

def matrix_multiply(A, B):
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])

    if cols_A != rows_B:
        print("Invalid matrices for multiplication.")
        return None

    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result






##### (iii) Using numpy

In [ ]:
import numpy as np

def matrix_multiply(A, B):
    result = np.dot(A, B)
    return result



##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
import numpy as np

def isValid(A, B):
    return A.shape[1] == B.shape[0]

def matrix_multiply_2(A, B):
    result = np.dot(A, B)
    return result



A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loop: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")


Result using loop: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(data):
    return sum(data) / len(data)

In [ ]:
def calculate_std_dev(data, mean):

    squared_diff = sum((x - mean)**2 for x in data)
    variance = squared_diff / len(data)
    std_dev = variance**0.5
    return std_dev

In [ ]:

def zscore_normalize(data):

    mean = mean(data)
    std_dev = calculate_std_dev(data, mean)

    normalized_data = [(x - mean) / std_dev for x in data]
    return normalized_data



##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
 import numpy as np
def zscore_normalization(x):

    mean_value = np.mean(x)
    std_dev = np.std(x)

    # Perform Z-score normalization
    normalized_data = (x - mean_value) / std_dev

    return normalized_data




##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
import numpy as np

def zscore_normalization(data):

    mean_value = sum(data) / len(data)
    std_dev = (sum((x - mean_value) ** 2 for x in data) / len(data)) ** 0.5
    normalized_data = [(x - mean_value) / std_dev for x in data]
    return normalized_data

def zscore_normalization_numpy(data):

    normalized_data = (data - np.mean(data)) / np.std(data)
    return normalized_data

# Example usage:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]

# Using custom function
result_custom = zscore_normalization(x)
print(f"Result without using numpy: {result_custom}")

# Using NumPy function
result_numpy = zscore_normalization_numpy(np.array(x))
print(f"Result using numpy: {result_numpy}")



Result without using numpy: [-1.0675326683028088, -0.9974539373420117, -0.9974539373420117, -0.8105773214465528, -0.41346451266870277, -0.06307085786471743, 0.3106823739262003, 0.9180313755864415, 1.2217058764165623, 1.8991336090376005]
Result using numpy: [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
import numpy as np
def sigmoidfn(x):
  result=(1/(1+np.exp(-x)))
  return result

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
import numpy as np

def sigmoid_derivative(x):
    sigmoid_x = sigmoidfn(x)
    result = sigmoid_x * (1 - sigmoid_x)
    return result


##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
import numpy as np
def sigmoidfn(x):
  result=(1/(1+np.exp(-x)))
  return result
  def sigmoid_derivative(x):
    sigmoid_x = sigmoidfn(x)
    result = sigmoid_x * (1 - sigmoid_x)
    return result

x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {sigmoid_derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[1.23379350e-04 1.04993585e-01 6.64805667e-03 2.50000000e-01
  2.50000000e-01]
 [9.10221180e-04 6.64805667e-03 2.50000000e-01 2.50000000e-01
  2.50000000e-01]]


# Section 2: Playing with Pandas

###Read the csv file


In [ ]:
import pandas as pd
file_path = "https://drive.google.com/file/d/1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ/view?usp=drive_link"
df = pd.read_csv(file_path)



###Display the shape of data frame


In [ ]:
import pandas as pd
file_path = "https://drive.google.com/file/d/1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ/view?usp=drive_link"
df = pd.read_csv(file_path)

print(df.shape)

(123, 1032)


###Return an array containing names of all the columns

In [ ]:

import pandas as pd
file_path = "https://drive.google.com/file/d/1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ/view?usp=drive_link"
df = pd.read_csv(file_path)
column_names = df.columns.tolist()
print(column_names)

['<!DOCTYPE html><html><head><meta name="google" content="notranslate"><meta http-equiv="X-UA-Compatible" content="IE=edge;"><style nonce="mlx3u4LRJb9Z1ZoxgpWzDw">@font-face{font-family:\'Roboto\';font-style:italic;font-weight:400;src:url(//fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1Mu51xIIzc.ttf)format(\'truetype\');}@font-face{font-family:\'Roboto\';font-style:normal;font-weight:300;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmSU5fBBc9.ttf)format(\'truetype\');}@font-face{font-family:\'Roboto\';font-style:normal;font-weight:400;src:url(//fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxP.ttf)format(\'truetype\');}@font-face{font-family:\'Roboto\';font-style:normal;font-weight:500;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc9.ttf)format(\'truetype\');}@font-face{font-family:\'Roboto\';font-style:normal;font-weight:700;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc9.ttf)format(\'truetype\');}</style><meta name="referrer" content="ori

###Display the number of null values in each column of the dataframe``



In [ ]:
import pandas as pd
file_path = "https://drive.google.com/file/d/1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ/view?usp=drive_link"
df = pd.read_csv(file_path)

null_values = df.isnull().sum()
print("Number of null values in each column:")
print(null_values)

Number of null values in each column:
<!DOCTYPE html><html><head><meta name="google" content="notranslate"><meta http-equiv="X-UA-Compatible" content="IE=edge;"><style nonce="dKGTNykOBQ4M3hVRMmkXow">@font-face{font-family:'Roboto';font-style:italic;font-weight:400;src:url(//fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1Mu51xIIzc.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:300;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmSU5fBBc9.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;src:url(//fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxP.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:500;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc9.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc9.ttf)format('truetype');}</style><meta name="referr

###Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
import pandas as pd
file_id = "1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ"
file_path = f"https://drive.google.com/uc?id={file_id}"
df = pd.read_csv(file_path)

df['Combined_Column'] = df['Property'] + ' at ' + df['Pressure'].astype(str)

print(df[df['Combined_Column'] == 'H at 75.0'])
print(df[df['Combined_Column'] == 'S at 250.0'])


    Pressure Property  Liq_Sat  Vap_Sat  75     100     125     150     175  \
26      75.0        H  384.451   2663.0 NaN  2679.4  2728.9  2778.2  2827.4   

       200  ...     450  475     500  525     550  575     600  625     650  \
26  2876.6  ...  3382.7  NaN  3488.4  NaN  3595.8  NaN  3705.0  NaN  3815.9   

    Combined_Column  
26        H at 75.0  

[1 rows x 38 columns]
    Pressure Property  Liq_Sat  Vap_Sat  75  100  125     150     175     200  \
59     250.0        S   1.6071    7.052 NaN  NaN  NaN  7.1689  7.2886  7.4001   

    ...     450  475     500  525     550  575     600  625    650  \
59  ...  8.2686  NaN  8.4104  NaN  8.5453  NaN  8.6743  NaN  8.798   

    Combined_Column  
59       S at 250.0  

[1 rows x 38 columns]


###Find out the column with the highest number of missing values

In [ ]:

port pandas as pd
import requests
from io import StringIO

# Replace the file_path with the correct Google Drive file ID
file_id = "1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ"
file_path = f"https://drive.google.com/uc?id={file_id}"

# Download the CSV content
response = requests.get(file_path)
csv_content = StringIO(response.text)

# Read the CSV content into a DataFrame
df = pd.read_csv(csv_content)

print(f"\nThe column with the highest number of missing values is: {column_with_most_nulls}")

NameError: ignored

###What is the average enthalpy of Sat. Liq. at all different pressures in the dataset ?

In [ ]:
import pandas as pd


file_path = "https://drive.google.com/file/d/1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ/view?usp=drive_link"
df = pd.read_csv(file_path)

# Filter the DataFrame for Sat. Liq.
sat_liq_df = df[df['Phase'] == 'Sat. Liq.']

# Calculate the average enthalpy for Sat. Liq.
average_enthalpy = sat_liq_df['Enthalpy (kJ/kg)'].mean()

# Display the result
print("Average enthalpy of Sat. Liq. at all different pressures:", average_enthalpy)

###Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:

import pandas as pd
import requests
from io import StringIO

# Replace the file_path with the correct Google Drive file ID
file_id = "1wmO9RlZYtI0I0vPZj6ab5_km1cQY96zZ"
file_path = f"https://drive.google.com/uc?id={file_id}"

# Download the CSV content
response = requests.get(file_path)
csv_content = StringIO(response.text)

# Read the CSV content into a DataFrame
df = pd.read_csv(csv_content)


V_data = df['V']
U_data = df['U']
H_data = df['H']
S_data = df['S']

# Display the first few rows of each separated data
print("V_data:")
print(V_data.head())

print("\nU_data:")
print(U_data.head())

print("\nH_data:")
print(H_data.head())

print("\nS_data:")
print(S_data.head())

#Section 3: PLotting the PLOTS

###Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Assume some sample data for illustration
pressure = np.linspace(0.1, 2.0, 100)
specific_volume = 1 / pressure
specific_internal_energy = np.sqrt(pressure)
specific_enthalpy = pressure ** 2
specific_entropy = np.log(pressure)
# Create subplots
fig, axs = plt.subplots(2, 2, figsize=(10, 8))

# Plot specific volume vs Pressure
axs[0, 0].plot(pressure, specific_volume, marker='o', markersize=5)
axs[0, 0].set_title('Specific Volume vs Pressure')
axs[0, 0].set_xlabel('Pressure')
axs[0, 0].set_ylabel('Specific Volume')

# Plot specific internal energy vs Pressure
axs[0, 1].plot(pressure, specific_internal_energy, marker='s', markersize=5)
axs[0, 1].set_title('Specific Internal Energy vs Pressure')
axs[0, 1].set_xlabel('Pressure')
axs[0, 1].set_ylabel('Specific Internal Energy')

# Plot specific enthalpy vs Pressure
axs[1, 0].plot(pressure, specific_enthalpy, marker='^', markersize=5)
axs[1, 0].set_title('Specific Enthalpy vs Pressure')
axs[1, 0].set_xlabel('Pressure')
axs[1, 0].set_ylabel('Specific Enthalpy')

# Plot specific entropy vs Pressure
axs[1, 1].plot(pressure, specific_entropy, marker='d', markersize=5)
axs[1, 1].set_title('Specific Entropy vs Pressure')
axs[1, 1].set_xlabel('Pressure')
axs[1, 1].set_ylabel('Specific Entropy')

# Adjust layout for better appearance
plt.tight_layout()

# Show the plot
plt.show()

###Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Example data (replace with actual data or equations)
pressure_range = np.linspace(300, 1500, 100)
specific_volume_data = 0.001 / pressure_range  # Example relationship for specific volume

# Plotting the specific volume vs Pressure
plt.plot(pressure_range, specific_volume_data, marker='o', markersize=5)
plt.title('Specific Volume of Saturated Liquid')
plt.xlabel('Pressure (kPa)')
plt.ylabel('Specific Volume (m^3/kg)')
plt.grid(True)
plt.show()

#Linear Regression
You're given a 100 data points generated from the function
$y=mx+c$. Some noise is added to the y values.

**Task:** Estimate the values of m and c using linear regression. Write a suitable cost function and update the parameters.

In [ ]:

import numpy as np
import matplotlib.pyplot as plt

# Generation of data points
np.random.seed(42)  # Setting seed for reproducibility
x = np.random.rand(100) * 100
y = -4 * x + 15
y = y + np.random.randn(100) * 30
plt.scatter(x, y)



In [ ]:
## Initial values for parameters
m = 0
c = 0

# Learning rate and number of iterations
learning_rate = 0.0001
iterations = 1000

# Cost function (Mean Squared Error)
def cost_function(x, y, m, c):
    n = len(y)
    predictions = m * x + c
    cost = (1 / (2 * n)) * np.sum((predictions - y) ** 2)
    return cost



Run the model

In [ ]:

# Gradient descent to update parameters
for _ in range(iterations):
    # Compute partial derivatives
    dm = (1 / len(y)) * np.sum((m * x + c - y) * x)
    dc = (1 / len(y)) * np.sum(m * x + c - y)

    # Update parameters
    m = m - learning_rate * dm
    c = c - learning_rate * dc

    # Print cost every 100 iterations
    if _ % 100 == 0:
        print(f"Iteration {_}, Cost: {cost_function(x, y, m, c)}")

In [ ]:

# Plotting the regression line
plt.plot(x, m * x + c, color='red', label='Regression Line')
plt.legend()
plt.show()

# Print the final values of m and c
print(f"Estimated values: m = {m}, c = {c}")